### ISSUE TITLE
Fails to render if $conf["start"] is empty

### ISSUE THREAD

**Issue by eduardomozart** [tormec/AcMenu#12]
Hello,
The DokuWiki Configurator uses the ``start`` by default and if the user attempts to empty it, it automatically fallback to ``start`` again, but the AcMenu stops to rendering the tree. I believe it's happening because even the DokuWiki configuration showing the default value of ``$conf["start"]`` to the end user at the DokuWiki Configurator, it's still an empty value at the config file. AcMenu should handle this falling back to the default value (``start``) if the value of ``$conf["start"]`` isn't set.

**Comment by tormec** [comment]
How did you manage to empty the startpage field?
DokuWiki doesn't allow you to save that variable as an empty one.

![image](https://user-images.githubusercontent.com/10964663/216682847-6ce3d1ed-e9bd-4ae1-87d1-bfc7de43eef0.png)

**Comment by eduardomozart** [comment]
Strange, I was able to. Not a big issue though.
