### ISSUE TITLE
incompatible to sprintdoc  template

### ISSUE THREAD

**Issue by edwardcodelab** [tormec/AcMenu#18]
acmenu plugin keeps crashing with sprintdoc template. I desperately need to either disable the template or acmenu plugin, and then delete all the cache to deal with the null array error at line 390 in acmenu code.

**Comment by tormec** [comment]
> I desperately need to either disable the template or acmenu plugin

If you have access to `/lib/plugins`, you can manually remove the acmenu' s folder.

> null array error at line 390 in acmenu code

I'll try to reproduce this issue with that template.

**Comment by ImSellingTheseFineLeatherJackets** [comment]
I'm also affected by that issue, first in line 390, then in line 405. I'm using the sprintdoc template too:
`2023-10-30 10:31:54
E_WARNING: in_array() expects parameter 2 to be array, null given
/var/www/html/dokuwiki/lib/plugins/acmenu/syntax.php(390)
#0 [internal function]: dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/dokuwiki/lib/plugins/acmenu/syntax.php(390): in_array()
#2 /var/www/html/dokuwiki/lib/plugins/acmenu/syntax.php(410): syntax_plugin_acmenu->_print()
#3 /var/www/html/dokuwiki/lib/plugins/acmenu/syntax.php(151): syntax_plugin_acmenu->_print()
#4 /var/www/html/dokuwiki/inc/parser/renderer.php(119): syntax_plugin_acmenu->render()
#5 /var/www/html/dokuwiki/inc/parserutils.php(700): Doku_Renderer->plugin()
#6 /var/www/html/dokuwiki/inc/parserutils.php(158): p_render()
#7 /var/www/html/dokuwiki/inc/parserutils.php(96): p_cached_output()
#8 /var/www/html/dokuwiki/inc/template.php(1592): p_wiki_xhtml()
#9 /var/www/html/dokuwiki/lib/tpl/sprintdoc/Template.php(148): tpl_include_page()
#10 /var/www/html/dokuwiki/lib/tpl/sprintdoc/tpl/main-sidebar-nav.php(2): dokuwiki\template\sprintdoc\Template->getNavigation()
#11 /var/www/html/dokuwiki/lib/tpl/sprintdoc/main.php(238): include('/var/www/html/d...')
#12 /var/www/html/dokuwiki/inc/actions.php(27): include('/var/www/html/d...')
#13 /var/www/html/dokuwiki/doku.php(126): act_dispatch()
#14 {main}
2023-10-30 10:31:54`

`E_WARNING: in_array() expects parameter 2 to be array, null given
/var/www/html/dokuwiki/lib/plugins/acmenu/syntax.php(405)
#0 [internal function]: dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/dokuwiki/lib/plugins/acmenu/syntax.php(405): in_array()
#2 /var/www/html/dokuwiki/lib/plugins/acmenu/syntax.php(410): syntax_plugin_acmenu->_print()
#3 /var/www/html/dokuwiki/lib/plugins/acmenu/syntax.php(151): syntax_plugin_acmenu->_print()
#4 /var/www/html/dokuwiki/inc/parser/renderer.php(119): syntax_plugin_acmenu->render()
#5 /var/www/html/dokuwiki/inc/parserutils.php(700): Doku_Renderer->plugin()
#6 /var/www/html/dokuwiki/inc/parserutils.php(158): p_render()
#7 /var/www/html/dokuwiki/inc/parserutils.php(96): p_cached_output()
#8 /var/www/html/dokuwiki/inc/template.php(1592): p_wiki_xhtml()
#9 /var/www/html/dokuwiki/lib/tpl/sprintdoc/Template.php(148): tpl_include_page()
#10 /var/www/html/dokuwiki/lib/tpl/sprintdoc/tpl/main-sidebar-nav.php(2): dokuwiki\template\sprintdoc\Template->getNavigation()
#11 /var/www/html/dokuwiki/lib/tpl/sprintdoc/main.php(238): include('/var/www/html/d...')
#12 /var/www/html/dokuwiki/inc/actions.php(27): include('/var/www/html/d...')
#13 /var/www/html/dokuwiki/doku.php(126): act_dispatch()
#14 {main}`

**Comment by ImSellingTheseFineLeatherJackets** [comment]
Addition: The Problem only occurs for normal users, not administrators.
