### ISSUE TITLE
Can't open category pages including start page

### ISSUE THREAD

**Issue by felinira** [tormec/AcMenu#3]
I want to open the category pages themselves but clicking on the only opens/closes the menu

**Comment by felinira** [comment]
It was my theme actually that was kinda buggy. Sorry. It works fine as long as the category page is called start.

**Comment by tormec** [comment]
> It works fine as long as the category page is called start.

Actually, AcMenu read the name of the [start](https://www.dokuwiki.org/config:startpage) page from the variable `$conf["start"]`, which is set in your Configuration Manager so you can call it as you want (`index`, `overview`, ...).

Note that, if you change the value of that variable you also have to rename all the affected pages in all namespaces.
