### ISSUE TITLE
AcMenu Not Using PageName in visible part of URL

### ISSUE THREAD

**Issue by 97Cweb** [tormec/AcMenu#4]
Good evening sir or madam.
I have been using AcMenu for the past week or so and would like to say it is amazing! It really helps with submenu navigation in a very easy to use manner.
I am running into an issue with it though. It currently pulls the pagename as written in the URL, so pages that have spaces end up with _ in between the words, and capitalization is ignored.
I am not sure if it is an issue with my naming structure, a bug, or a feature, but I noticed in your animated gif on the main page (not on GitHub) that it does support spaces and capitalization

Please help
Thank you
![Annotation 2020-04-13 201055](https://user-images.githubusercontent.com/63621179/79172522-f7a2f200-7dc2-11ea-9f8f-6cd81a74e1f5.png)

**Comment by tormec** [comment]
In your Configuration Manager set the value of [useheading](https://www.dokuwiki.org/config:useheading) to `Always`.

**Comment by 97Cweb** [comment]
Thank you for this, and for the quick reply
Have a good day
