### ISSUE TITLE
How to exclude namespaces

### ISSUE THREAD

**Issue by regis-syntesis** [tormec/AcMenu#5]
Hi, I'm reading the documentation and saw that this plugin supports the hidepages options.
I'm trying to hide wiki and playground namespaces, but I can't figure out how to do this.
Please, someone can help me do this?

**Comment by tormec** [comment]
The DokuWiki documentation  about [hidepages](https://www.dokuwiki.org/config:hidepages) says that that option is for *pages* (not for namespaces).
Wiki and Playground namespaces con only be hidden through [ACL](https://www.dokuwiki.org/acl) but take in mind that ACL doesn't allow you to hide to the Admin any namespace.
The AcMenu plugin doesn't change this behaviour.

**Comment by regis-syntesis** [comment]
Thanks for the quick reply, I will look into that!
